### ISSUE TITLE
Fresh install results in OSError: [Errno 2] ENOENT

### ISSUE THREAD

**Issue by aeonik** [RedBalloonShenanigans/antenny#102]
Hello,
I followed the following steps:
```
esptool.py --port /dev/ttyUSB0 erase_flash
esptool.py --chip esp32 --port /dev/ttyUSB0 write_flash -z 0x1000 esp32spiram-20210623-v1.16.bin
make nyansat SERIAL=/dev/ttyUSB0
screen /dev/ttyUSB0 115200
```
After trying to boot I am getting the following error:
```
time.monotonic() not available in python < 3.3, using time.time() as fallback
Traceback (most recent call last):
  File "main.py", line 18, in <module>
  File "main.py", line 13, in start
  File "api/api.py", line 37, in __init__
  File "config/config.py", line 15, in __init__
  File "config/config.py", line 38, in _get_default_config
OSError: [Errno 2] ENOENT
MicroPython v1.14 on 2021-02-02; ESP32 module (spiram) with ESP32
Type "help()" for more information.
>>> 
```

I have tried two different firmware versions:
- esp32spiram-20210623-v1.16.bin
- esp32spiram-idf3-20210202-v1.14.bin

Should I try a different firmware version, or is there some other way to work around this issue?

**Comment by dannyp303** [comment]
Hi, I will make this more clear in the install steps as well as in the documentation, but on your first install, you should select `No` for `Do you want to keep the configs on the device? (Y/n)` as your device currently has no configs on it.
