### ISSUE TITLE
"ModuleNotFoundError: No module named 'mp'" When running make command

### ISSUE THREAD

**Issue by InkRF** [RedBalloonShenanigans/antenny#103]
When running the `make nyansat SERIAL=/dev/ttyUSB0` from the root directory of the repo , I retrieve the following error:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kali/antenny/nyansat/station/installer/__main__.py", line 13, in <module>
    from mp.mpfexp import RemoteIOError, ConError
ModuleNotFoundError: No module named 'mp'
```

While I haven't worked with Python before, I see that its missing or can't find several module/files in the repo. After commenting out line 13 in `./antenny/nyansat/station/installer/__main__.py` just to see what happens, it does the same again where it can't find the nyansat module.

I'm not quite sure what I should do from here, I've re-cloned the repo to no avail so now I'm coming here for guidance. 
Cheers

**Comment by dannyp303** [comment]
Hello, MPFShell is a dependency. It is used to interact with the antenny board from you host computer.  To install it you have to run `python3 -m pip install mpfshell`. If you haven't worked with python before you might also have to install pip. Instructions for this can be found [here](https://pip.pypa.io/en/stable/installation/).

**Comment by InkRF** [comment]
Just got it sorted out, didn't have the mpfshell module installed on this computer. May be good to include that requirements in the README as well

**Comment by dannyp303** [comment]
Yep, its mentioned at the tail end, but I will add it to the setup steps.
