### ISSUE TITLE
V1 vs V2 vs Breadboard configs differ

### ISSUE THREAD

**Issue by cameronbosnic** [RedBalloonShenanigans/antenny#45]
Not sure how you want to handle it  but the pin configs are different per board now with the most recent update.  You can't load a custom config with the nyansat console until antkontrol is initialized, which it can't do because the setup fails.

**Comment by cameronbosnic** [comment]
I'd recommend changing the load order to allow a config to be loaded before initialization happens, and have 3 default pin configs that folks can load depending on which version of the hardware they have.

**Comment by ruffruffruffie** [comment]
Thank you for bringing this issue up; to address this, we are:
- Creating a special "SAFE MODE" operating condition for AntKontrol
- Decoupling the configuration system from AntKontrol
- Providing more thorough documentation to help users set up their devices

In addition, we will be looking into your 3 default pin configuration solution!

**Comment by cameronbosnic** [comment]
Ok, yeah like the safe mode idea.  Saw that you were doing a refactor. Thanks!

**Comment by ruffruffruffie** [comment]
Hey cameronbosnic! We're staging in the 3 default pin configuration idea for today; we plan on including 2 additional configuration files for the `diy` and `av1` options to complement the default configuration, which reflects Antenny V2's pins.

**Comment by cameronbosnic** [comment]
Linking back to the commit https://github.com/RedBalloonShenanigans/antenny/commit/cc01d3cf4b61a988bb08ef60eb8f5f911c65b000

**Comment by ruffruffruffie** [comment]
Keen eye! We have started work around including an `antenny_board_version` parameter in the configurations to disable certain pins. To comprehensively address this issue, we are also going to add in the additional two configuration files; this should be a relatively simple addition.

**Comment by ruffruffruffie** [comment]
Preloaded configuration files have been added!
