### ISSUE TITLE
Put lat/long in config.py for non GPS users

### ISSUE THREAD

**Issue by cameronbosnic** [RedBalloonShenanigans/antenny#69]
There should be a config option for setting lat and long manually for users who are not using a gps in their setup.

**Comment by ruffruffruffie** [comment]
Brilliant idea! Should be a simple addition, we will put it on our todo list.

**Comment by cameronbosnic** [comment]
Looks like work has started on this with https://github.com/RedBalloonShenanigans/antenny/pull/73 thanks!

**Comment by ruffruffruffie** [comment]
Yup! It should be merged in to `master` branch as of last night!

**Comment by ruffruffruffie** [comment]
I'll wait for confirmation from you to close this issue
