### ISSUE TITLE
Please export gerbers to allow for easy duplication

### ISSUE THREAD

**Issue by pk-mdt** [RedBalloonShenanigans/antenny#85]
Could you please export gerbers to allow for easy fabrication using oshpark or a similar service? I exported v2 using a temp license but do not have a full license to export the newest versions. The version I created as a prototype is missing the mask areas for the USB connector, which has been corrected in a newer version.

**Comment by 0xac** [comment]
Yup, we'll do that tomorrow. Hans is also rolling out v3, which now uses a
ESP32 module with additional SPI RAM.

**Comment by pk-mdt** [comment]
Gerbers exported
